export const UPDATE_NAME = "UPDATE_NAME";
export const UPDATE_CARD_NUMBER = "UPDATE_CARD_NUMBER";
export const UPDATE_CARD_MONTH = "UPDATE_CARD_MONTH";
export const UPDATE_CARD_YEAR = "UPDATE_CARD_YEAR";
export const UPDATE_CARD_CVV = "UPDATE_CARD_CVV";
